using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Wallet.Application.Interfaces;
using Wallet.Core.Entities;

[ApiController]
[Route("api/[controller]")]
public class RulesController : ControllerBase
{
    private readonly IConfigurationRuleRepository _ruleRepo;

    public RulesController(IConfigurationRuleRepository ruleRepo)
    {
        _ruleRepo = ruleRepo;
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<ConfigurationRule>>> GetAll(CancellationToken ct)
    {
        var rules = await _ruleRepo.GetAllAsync(ct);
        return Ok(rules);
    }

    [HttpGet("{id:guid}")]
    public async Task<ActionResult<ConfigurationRule>> Get(Guid id, CancellationToken ct)
    {
        var r = await _ruleRepo.GetByIdAsync(id, ct);
        if (r == null) return NotFound();
        return Ok(r);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] ConfigurationRule rule, CancellationToken ct)
    {
        // rule.Id generated by constructor or let EF handle
        await _ruleRepo.AddAsync(rule, ct);
        await _ruleRepo.SaveChangesAsync(ct);
        return CreatedAtAction(nameof(Get), new { id = rule.Id }, rule);
    }

    [HttpPut("{id:guid}")]
    public async Task<IActionResult> Update(Guid id, [FromBody] ConfigurationRule dto, CancellationToken ct)
    {
        var existing = await _ruleRepo.GetByIdAsync(id, ct);
        if (existing == null) return NotFound();

        // update allowed properties
        existing.RuleType = dto.RuleType;
        existing.PointsPerBaseAmount = dto.PointsPerBaseAmount;
        existing.BaseAmount = dto.BaseAmount;
        existing.IsDefault = dto.IsDefault;

        _ruleRepo.Update(existing);
        await _ruleRepo.SaveChangesAsync(ct);
        return NoContent();
    }

    [HttpDelete("{id:guid}")]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct)
    {
        await _ruleRepo.DeleteAsync(id, ct);
        await _ruleRepo.SaveChangesAsync(ct);
        return NoContent();
    }
}
